/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-session-ui/xml/org.lingmo.Gesture1.xml -a ./dde-session-ui/toolGenerate/qdbusxml2cpp/org.lingmo.Gesture1Adaptor -i ./dde-session-ui/toolGenerate/qdbusxml2cpp/org.lingmo.Gesture1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-session-ui/toolGenerate/qdbusxml2cpp/org.lingmo.Gesture1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Gesture1Adaptor
 */

Gesture1Adaptor::Gesture1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Gesture1Adaptor::~Gesture1Adaptor()
{
    // destructor
}

